<?xml version="1.0"?>
<!DOCTYPE TVSCHEDULE [
<!ELEMENT TVSCHEDULE (CHANNEL+)>
<!ELEMENT CHANNEL (BANNER,DAY+)>
<!ELEMENT BANNER (#PCDATA)>
<!ELEMENT DAY (DATE,(HOLIDAY|PROGRAMSLOT+)+)>
<!ELEMENT HOLIDAY (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT PROGRAMSLOT (TIME,TITLE,DESCRIPTION?)>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
<!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
<!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
<!ATTLIST TITLE RATING CDATA #IMPLIED>
<!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>
]>
<TVSCHEDULE NAME="Antena 3">
    <CHANNEL CHAN="3">
        <BANNER>Si</BANNER>
        <DAY>
            <DATE>7 de Febrero</DATE>
            <PROGRAMSLOT>
                <TIME>12</TIME>
                <TITLE LANGUAGE="ES">La que se avecina</TITLE>
                <DESCRIPTION>Programa comico</DESCRIPTION>
                
            </PROGRAMSLOT>
        </DAY>
        <DAY>
            <DATE>8 de febrero</DATE>
            <HOLIDAY>Aqui no hay quien viva</HOLIDAY>
        </DAY>
    </CHANNEL>
</TVSCHEDULE>